version: '3'
services:
  postgresdb:
    image: "postgres"
    container_name: postgresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    volumes:
      - database-data:/database-data
volumes:
  database-data:
